name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: code

    - name: Decode and add google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo "$GOOGLE_SERVICES_JSON" | base64 --decode > code/app/google-services.json

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: code

    - name: Run Unit Tests
      run: ./gradlew test
      working-directory: code
